// import { useRouter } from "next/router";
// import Head from "next/head";
// const Index = () => {
//   const router = useRouter();
//   useEffect(() => {
//     router.push("/login");
//   }, []);
//   return (
//     <>
//       <Head>
//         <title>Legal</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//     </>
//   );
// };

// export default Index;
