"use client";

import { Inter } from "next/font/google";
import "./globals.css";
import LoginPage from "./login/page";

import { ChakraProvider } from "@chakra-ui/react";
import { ChatProvider } from "@/utils/context_api/ChatContext";
import { SidebarProvider } from "@/utils/context_api/SidebarContext";

const inter = Inter({ subsets: ["latin"] });

import { Providers } from "./providers";
import Navbar from "@/components/landing-page/Navbar";
import Head from "next/head";

// export const metadata = {
//   title: "Legal",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html>
      <Head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
          window.dataLayer = window.dataLayer || [];
          function gtag() { dataLayer.push(arguments); }
          gtag('js', new Date());
          gtag('config', 'G-BCH4X9ZDED');
        `,
          }}
        />
        <title>Optillus Legal AI</title>
        <meta
          name="description"
          content="Explore the power of Optillus Legal AI for efficient legal research, persuasive argument crafting, and more."
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/app/favicon.ico" />
        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-BCH4X9ZDED"
        ></script>

        <script
          dangerouslySetInnerHTML={{
            __html: `
                    !function(f,b,e,v,n,t,s)
                    {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
                    n.callMethod.apply(n,arguments):n.queue.push(arguments)};
                    if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
                    n.queue=[];t=b.createElement(e);t.async=!0;
                    t.src=v;s=b.getElementsByTagName(e)[0];
                    s.parentNode.insertBefore(t,s)}(window, document,'script',
                    'https://connect.facebook.net/en_US/fbevents.js');
                    fbq('init', 'YOUR_PIXEL_ID');
                    fbq('track', 'PageView');
                `,
          }}
        />
      </Head>
      <body className="overflow-x-hidden">
        <Providers>
          <SidebarProvider>
            <ChatProvider>
              <ChakraProvider>{children}</ChakraProvider>
            </ChatProvider>
          </SidebarProvider>
        </Providers>
      </body>
    </html>
  );
}
